import { PIN_ID } from './pinnedRegistry';
import { DITHER_METHOD } from '../stores/engine/ditherStore';

export const TEMPLATES = [
  {
    id: 'default',
    name: 'DEFAULT',
    badge: 'BALANCED',
    description: 'Standard studio configuration with natural colors and Floyd-Steinberg dither.',
    palette: {
      id: null,
      name: 'DEFAULT',
      colors: ['#000000', '#444444', '#888888', '#cccccc', '#ffffff'],
      colorCount: 5,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.FLOYD_STEINBERG,
      amount: 0.65,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 1.0,
      blacks: 0.0,
      whites: 0.0,
      contrast: 0.0,
      saturation: 1.0,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.COLOR_GAMMA,
      PIN_ID.COLOR_BLACKS,
      PIN_ID.COLOR_WHITES,
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.COLOR_SATURATION,
      PIN_ID.DITHER_AMOUNT,
    ],
  },
  {
    id: '1bit',
    name: '1-BIT MONOCHROME',
    badge: 'HIGH CONTRAST',
    description: 'Crisp 2-color black & white newspaper dither with enhanced dynamic range.',
    palette: {
      id: 'template-1bit',
      name: '1-Bit B&W',
      colors: ['#000000', '#ffffff'],
      colorCount: 2,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.FLOYD_STEINBERG,
      amount: 0.85,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 0.95,
      blacks: -0.05,
      whites: 0.05,
      contrast: 25.0,
      saturation: 0.0,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.COLOR_BLACKS,
      PIN_ID.COLOR_WHITES,
      PIN_ID.COLOR_GAMMA,
      PIN_ID.DITHER_AMOUNT,
    ],
  },
  {
    id: 'gameboy',
    name: 'GAME BOY DMG',
    badge: '4-SHADE RETRO',
    description: 'Authentic 4-shade greenish palette with classic Nintendo handheld ordered dither.',
    palette: {
      id: 'builtin-gameboy',
      name: 'Game Boy',
      colors: ['#0f380f', '#306230', '#8bac0f', '#9bbc0f'],
      colorCount: 4,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.ORDERED_BAYER,
      amount: 0.8,
      matrixScale: 2.0,
      seed: 1.0,
    },
    params: {
      gamma: 1.05,
      blacks: -0.02,
      whites: 0.04,
      contrast: 20.0,
      saturation: 1.0,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.DITHER_AMOUNT,
      PIN_ID.DITHER_MATRIX_SCALE,
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.COLOR_GAMMA,
      PIN_ID.RESIZE_SCALE,
    ],
  },
  {
    id: 'cga',
    name: 'CGA MODE 1',
    badge: '1981 DOS',
    description: 'Iconic IBM PC Cyan, Magenta, White and Black retro computing aesthetic.',
    palette: {
      id: 'builtin-cga4',
      name: 'CGA Palette 1',
      colors: ['#000000', '#55ffff', '#ff55ff', '#ffffff'],
      colorCount: 4,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.ATKINSON,
      amount: 0.75,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 1.0,
      blacks: 0.0,
      whites: 0.0,
      contrast: 15.0,
      saturation: 1.3,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.COLOR_SATURATION,
      PIN_ID.DITHER_AMOUNT,
      PIN_ID.RESIZE_SCALE,
    ],
  },
  {
    id: 'cyberpunk',
    name: 'CYBERPUNK NEON',
    badge: 'SYNTHWAVE',
    description: 'Vibrant neon cyan, hot magenta and dark violet tones with fine error diffusion.',
    palette: {
      id: 'template-cyberpunk',
      name: 'Cyberpunk Neon',
      colors: ['#0d0221', '#0f084b', '#26408b', '#a60067', '#00ebc7', '#ff007f', '#fbf5f3'],
      colorCount: 7,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.SIERRA,
      amount: 0.7,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 0.9,
      blacks: -0.04,
      whites: 0.06,
      contrast: 30.0,
      saturation: 1.4,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.COLOR_SATURATION,
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.COLOR_GAMMA,
      PIN_ID.DITHER_AMOUNT,
    ],
  },
  {
    id: 'macintosh',
    name: 'MACINTOSH 1984',
    badge: 'ATKINSON 1-BIT',
    description: 'Classic Bill Atkinson 1-bit dither algorithm originally designed for original Apple Mac.',
    palette: {
      id: 'template-mac',
      name: 'Macintosh 1-bit',
      colors: ['#000000', '#ffffff'],
      colorCount: 2,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.ATKINSON,
      amount: 0.9,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 0.9,
      blacks: -0.02,
      whites: 0.02,
      contrast: 20.0,
      saturation: 0.0,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.DITHER_AMOUNT,
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.COLOR_BLACKS,
      PIN_ID.COLOR_WHITES,
      PIN_ID.RESIZE_SCALE,
    ],
  },
  {
    id: 'amber-crt',
    name: 'AMBER TERMINAL',
    badge: 'CRT PHOSPHOR',
    description: 'Warm glowing monochrome amber tones reminiscent of classic mainframe terminals.',
    palette: {
      id: 'template-amber',
      name: 'Amber CRT',
      colors: ['#100800', '#4a2500', '#9c5500', '#ffb000'],
      colorCount: 4,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.ORDERED_BAYER,
      amount: 0.75,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 1.1,
      blacks: -0.05,
      whites: 0.05,
      contrast: 25.0,
      saturation: 1.2,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.COLOR_GAMMA,
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.DITHER_AMOUNT,
      PIN_ID.DITHER_MATRIX_SCALE,
    ],
  },
];
