import { PIN_ID } from './pinnedRegistry';
import { DITHER_METHOD } from '../stores/engine/ditherStore';

export const TEMPLATES = [
  {
    id: 'default',
    name: 'DEFAULT',
    author: 'xbvuno',
    palette: {
      id: null,
      name: 'DEFAULT',
      extractMethod: 'median_cut',
      colorCount: 8,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.FLOYD_STEINBERG,
      amount: 0.65,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 0.85,
      blacks: 0.0,
      whites: 0.0,
      contrast: 0.0,
      saturation: 1.0,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.COLOR_GAMMA,
      PIN_ID.COLOR_BLACKS,
      PIN_ID.COLOR_WHITES,
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.COLOR_SATURATION,
      PIN_ID.COLOR_HUE,
      PIN_ID.DITHER_AMOUNT,
      PIN_ID.RESIZE_SCALE,
    ],
  },
  {
    id: '1bit',
    name: '1-BIT',
    author: 'xbvuno',
    palette: {
      id: 'template-1bit',
      name: '1-Bit B&W',
      colors: ['#000000', '#ffffff'],
      colorCount: 2,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.FLOYD_STEINBERG,
      amount: 0.55,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 0.95,
      blacks: -0.05,
      whites: 0.05,
      contrast: 25.0,
      saturation: 0.0,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.COLOR_GAMMA,
      PIN_ID.COLOR_BLACKS,
      PIN_ID.COLOR_WHITES,
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.DITHER_AMOUNT,
      PIN_ID.RESIZE_SCALE,
    ],
  },
  {
    id: 'gameboy',
    name: 'GAME BOY DMG',
    author: 'xbvuno',
    palette: {
      id: 'builtin-gameboy',
      name: 'Game Boy',
      colors: ['#0f380f', '#306230', '#8bac0f', '#9bbc0f'],
      colorCount: 4,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.ORDERED_BAYER,
      amount: 0.25,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 1.05,
      blacks: -0.02,
      whites: 0.04,
      contrast: 20.0,
      saturation: 1.0,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.COLOR_GAMMA,
      PIN_ID.COLOR_BLACKS,
      PIN_ID.COLOR_WHITES,
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.COLOR_SATURATION,
      PIN_ID.COLOR_HUE,
      PIN_ID.DITHER_AMOUNT,
      PIN_ID.RESIZE_SCALE,
    ],
  },
  {
    id: 'cga',
    name: 'CGA MODE 1',
    author: 'xbvuno',
    palette: {
      id: 'builtin-cga4',
      name: 'CGA Palette 1',
      colors: ['#000000', '#55ffff', '#ff55ff', '#ffffff'],
      colorCount: 4,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.ATKINSON,
      amount: 0.75,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 1.0,
      blacks: 0.0,
      whites: 0.0,
      contrast: 15.0,
      saturation: 1.3,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.COLOR_GAMMA,
      PIN_ID.COLOR_BLACKS,
      PIN_ID.COLOR_WHITES,
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.COLOR_SATURATION,
      PIN_ID.COLOR_HUE,
      PIN_ID.DITHER_AMOUNT,
      PIN_ID.RESIZE_SCALE,
    ],
  },
  {
    id: 'cyberpunk',
    name: 'CYBERPUNK NEON',
    author: 'xbvuno',
    palette: {
      id: 'template-cyberpunk',
      name: 'Cyberpunk Neon',
      colors: ['#0d0221', '#0f084b', '#26408b', '#a60067', '#00ebc7', '#ff007f', '#fbf5f3'],
      colorCount: 7,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.SIERRA,
      amount: 0.7,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 0.9,
      blacks: -0.04,
      whites: 0.06,
      contrast: 30.0,
      saturation: 1.4,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.COLOR_GAMMA,
      PIN_ID.COLOR_BLACKS,
      PIN_ID.COLOR_WHITES,
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.COLOR_SATURATION,
      PIN_ID.COLOR_HUE,
      PIN_ID.DITHER_AMOUNT,
      PIN_ID.RESIZE_SCALE,
    ],
  },
  {
    id: 'amber-crt',
    name: 'AMBER TERMINAL',
    author: 'xbvuno',
    palette: {
      id: 'template-amber',
      name: 'Amber CRT',
      colors: ['#100800', '#4a2500', '#9c5500', '#ffb000'],
      colorCount: 4,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.ORDERED_BAYER,
      amount: 0.75,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 1.1,
      blacks: -0.05,
      whites: 0.05,
      contrast: 25.0,
      saturation: 1.2,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.COLOR_GAMMA,
      PIN_ID.COLOR_BLACKS,
      PIN_ID.COLOR_WHITES,
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.COLOR_SATURATION,
      PIN_ID.COLOR_HUE,
      PIN_ID.DITHER_AMOUNT,
      PIN_ID.RESIZE_SCALE,
    ],
  },
  {
    id: 'apollo16',
    name: 'APOLLO 16',
    author: 'xbvuno',
    palette: {
      id: 'builtin-apollo16',
      name: 'Apollo 16',
      colors: ['#172038', '#253a5e', '#3c5e8b', '#4f8fba', '#73bed3', '#a4dddb', '#19332d', '#25562e', '#468232', '#75a743', '#a8ca58', '#d0da91', '#4d2b32', '#7a4841', '#ad7757', '#c09473'],
      colorCount: 16,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.FLOYD_STEINBERG,
      amount: 0.65,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 1.0,
      blacks: 0.0,
      whites: 0.0,
      contrast: 10.0,
      saturation: 1.1,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.COLOR_GAMMA,
      PIN_ID.COLOR_BLACKS,
      PIN_ID.COLOR_WHITES,
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.COLOR_SATURATION,
      PIN_ID.COLOR_HUE,
      PIN_ID.DITHER_AMOUNT,
      PIN_ID.RESIZE_SCALE,
    ],
  },
  {
    id: 'sweetie16',
    name: 'SWEETIE 16',
    author: 'xbvuno',
    palette: {
      id: 'builtin-sweetie16',
      name: 'Sweetie 16',
      colors: ['#1a1c2c', '#5d275d', '#b13e53', '#ef7d57', '#ffcd75', '#a7f070', '#38b764', '#257179', '#29366f', '#3b5dc9', '#41a6f6', '#73eff7', '#f4f4f4', '#94b0c2', '#566c86', '#333c57'],
      colorCount: 16,
    },
    dither: {
      enabled: true,
      method: DITHER_METHOD.FLOYD_STEINBERG,
      amount: 0.65,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 1.0,
      blacks: 0.0,
      whites: 0.0,
      contrast: 10.0,
      saturation: 1.1,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [
      PIN_ID.COLOR_GAMMA,
      PIN_ID.COLOR_BLACKS,
      PIN_ID.COLOR_WHITES,
      PIN_ID.COLOR_CONTRAST,
      PIN_ID.COLOR_SATURATION,
      PIN_ID.COLOR_HUE,
      PIN_ID.DITHER_AMOUNT,
      PIN_ID.RESIZE_SCALE,
    ],
  },
  {
    id: 'no-changes',
    name: 'NO-CHANGES',
    author: 'xbvuno',
    palette: {
      id: null,
    },
    dither: {
      enabled: false,
      method: DITHER_METHOD.FLOYD_STEINBERG,
      amount: 0.0,
      matrixScale: 1.0,
      seed: 1.0,
    },
    params: {
      gamma: 1.0,
      blacks: 0.0,
      whites: 0.0,
      contrast: 0.0,
      saturation: 1.0,
      hue: 0.0,
      noiseEnabled: false,
      blurEnabled: false,
    },
    pinnedIds: [],
  },
];
